name: Build

on:
  push:
    paths-ignore:
      - "**.md"
      
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        channel:
          - nightly
        target-triple:
          - x86_64-unknown-linux-gnu
        include:
          - target-triple: x86_64-unknown-linux-gnu
            host-triple: x86_64-unknown-linux-gnu
            channel: nightly
            os: ubuntu-18.04
            
    name: Building ${{ matrix.channel }}-${{ matrix.target-triple }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1

      - name: 'Install ${{ matrix.channel }}-${{ matrix.host-triple }} for target: ${{ matrix.target-triple }}'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: ${{ matrix.target-triple }}

      - name: '`cargo test --release --target ${{ matrix.target-triple }}`'
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --target ${{ matrix.target-triple }}

      - name: '`cargo build --release --target ${{ matrix.target-triple }}`'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target-triple }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bitwarden_rs-${{ matrix.target-triple }}${{ matrix.ext }}
          path: target/${{ matrix.target-triple }}/release/bitwarden_rs${{ matrix.ext }}

