name: CI

on:
  push:
    tags:
      - '1.*'
  release:
    types: [ created ]

env:
  CARGO_TERM_COLOR: always
jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
   
    strategy:
      matrix:
        name: [ linux, macos]
        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/joff
            asset_name: joff-linux
          - name: macos
            os: macos-latest
            artifact_name: target/release/joff
            asset_name: joff-macos

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        rustup override set nightly
        cargo build --release --locked

    - name: Upload binaries to release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}
    
