name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

env:
  CARGO_TERM_COLOR: always
jobs:
  create_release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      publish
    steps:

        
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [ linux, macos]
        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/joff
            asset_name: joff-linux
          - name: macos
            os: macos-latest
            artifact_name: target/release/joff
            asset_name: joff-macos

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        rustup override set nightly
        cargo build --release --locked

    - name: Upload binaries to release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}
    
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    
    - name: Create Release
      id: create_release
      continue-on-error: true
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.slug.outputs.sha8 }}
        release_name: Release ${{ steps.slug.outputs.sha8 }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset-macos
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        asset_content_type: application/zip
    
