name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set to nightly
      run: rustup override set nightly
    - name: Build
      run: cargo build --verbose
    - name: Rust Release binary
      uses: Douile/rust-build.action@v0.1.26
      with:
        RUSTTARGET: ${{ matrix.target }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXTRA_FILES: "README.md LICENSE"
